sudo: required

services:
  - docker

before_install:
  - cd frontend
  - docker build -t grovejam/docker-kubernetes -f Dockerfile.dev ./

script:
  - docker run grovejam/docker-kubernetes npm run test -- --coverage
